name: app_data
description: Flutter package to manage the App Data.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  api_connection:
    path: ../api_connection
  utils:
    path: ../utils
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  rx_shared_preferences: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  formz: ^0.7.0