name: api_connection
description: Dart package to manage the API Communication.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  http: ^1.2.1
  http_client_helper: ^3.0.0
  http_interceptor: ^2.0.0-beta.8
  rx_shared_preferences: ^3.1.0
  json_annotation: ^4.6.0
  mime: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.3.1