name: login
description: Flutter package to manage the Login Module.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  my_theme:
    path: ../my_theme
  utils:
    path: ../utils
  custom_widgets:
    path: ../custom_widgets
  api_connection:
    path: ../api_connection
  app_data:
    path: ../app_data
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  formz: ^0.7.0
  app_links: ^6.3.2
  permission_handler: ^11.3.1

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
