name: utils
description: Flutter/Dart package to manage the Util methods.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  sprintf: ^7.0.0
  equatable: ^2.0.5
  path_provider: ^2.1.3